"""
fetcher.py
----------
Downloads historical price data for energy commodities via yfinance.

Tickers used:
  - WTI Crude Oil  : CL=F  (fallback: USO ETF)
  - Brent Crude Oil: BZ=F  (fallback: BNO ETF)
  - Natural Gas    : NG=F  (fallback: UNG ETF)
  - Coal           : KOL   (fallback: ARCH)
  - Electricity    : ICLN  (fallback: FSLR)

Prices are quoted in USD per unit (futures) or USD per share (ETFs).
"""

import yfinance as yf
import pandas as pd
from pathlib import Path

# Primary and fallback tickers for each commodity
COMMODITIES = {
    "WTI_Oil":     ["CL=F", "USO"],     # USD/barrel (futures) or USD/share (ETF)
    "Brent_Oil":   ["BZ=F", "BNO"],     # USD/barrel (futures) or USD/share (ETF)
    "Natural_Gas": ["NG=F", "UNG"],     # USD/MMBtu  (futures) or USD/share (ETF)
    "Coal":        ["KOL",  "ARCH"],    # USD/share  (ETF / equity)
    "Electricity": ["ICLN", "FSLR"],    # USD/share  (ETF / equity)
}

# Human-readable units for chart labels
UNITS = {
    "WTI_Oil":     "USD / barrel",
    "Brent_Oil":   "USD / barrel",
    "Natural_Gas": "USD / MMBtu",
    "Coal":        "USD / share",
    "Electricity": "USD / share",
}

DATA_DIR = Path(__file__).parent


def fetch(start: str = "2015-01-01", end: str | None = None) -> dict[str, pd.Series]:
    """
    Download adjusted close prices for each commodity.

    Parameters
    ----------
    start : str  – start date (YYYY-MM-DD)
    end   : str  – end date   (None = today)

    Returns
    -------
    dict  commodity_name -> pd.Series with DatetimeIndex
    """
    prices: dict[str, pd.Series] = {}
    for name, tickers in COMMODITIES.items():
        success = False
        for ticker in tickers:
            print(f"  Downloading {name} ({ticker})...")
            try:
                raw = yf.download(ticker, start=start, end=end, auto_adjust=True, progress=False)
                if raw.empty:
                    print(f"    -> No data for {ticker}, trying fallback...")
                    continue
                series = raw["Close"].squeeze().dropna()
                series.name = name
                prices[name] = series
                print(f"    OK {len(series)} observations downloaded.")
                success = True
                break
            except Exception as e:
                print(f"    -> Error with {ticker}: {e}")
        if not success:
            print(f"    WARNING: No ticker worked for {name} -- skipped.")
    return prices


def save(prices: dict[str, pd.Series], filename: str = "commodities.csv") -> Path:
    """Save all prices to a single CSV (one column per commodity)."""
    df = pd.DataFrame(prices)
    out = DATA_DIR / filename
    df.to_csv(out)
    print(f"  OK Data saved to {out}  ({df.shape[0]} rows, {df.shape[1]} columns)")
    return out


def load(filename: str = "commodities.csv") -> pd.DataFrame:
    """Load the CSV generated by save()."""
    path = DATA_DIR / filename
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    return df


if __name__ == "__main__":
    print("=== Downloading commodity data ===")
    prices = fetch(start="2015-01-01")
    save(prices)
